### ISSUE TITLE
Save each frame into a still image instead of h264 file

### ISSUE THREAD

**Issue by yongwang** [ngraziano/SharpRTSP#11]
Hi Nicolas,

Thanks for sharing this useful library!

A quick question regarding using this library, could it save each frame into a still image instead of .264 file?

`Process_RTP_Frame()` writes file stream as NAL, How can I extra the image from the raw bytes?

Thanks and regards,
Yong

**Comment by RogerHardiman** [comment]
Hi Yong

There are two parts to video streaming
  Part 1 - carrying data over a network. This is what SharpRTSP does.

  Part 2 - converting data (the NALs) back into still images. This is a job for a H264 decoder (a H264 decompression library) and is not something that SharpRTSP does.

There are several ways to convert NALs to still images.
Some people use classes provided by the operating system that use the hardware H264 decoders that are part of modern computer chipsets.
Some people use ffmpeg (a C library which is called as unmanaged code) to convert NALs to still images.

There is a C# port of part of ffmpeg called CSCodec project on github https://github.com/soywiz/cscodec but I don't know how good it is.


Anyway for your project you need to link to use SharpRTSP to get the NALs but then need to use something else to convert NALs into still images.

**Comment by RogerHardiman** [comment]
Hi Yong
In my last post I forgot to say this....

The reason RTSP just carries 'data' and does not know what to do with it is because RTSP can carry lots of different video formats (MPEG1, MPEG2, H263, MPEG4, H264, VP8, MJPEG etc) and lots of different audio formats (u-law, a-law, G711, G723, Speex, AAC, AMR, MP3 etc).

So RTSP just carries blocks of data. RTSP usually knows what type of data it is but RTSP does not know what to do with the data.

It is the application that has to take the 'data' from RTSP and convert the data into images and into sounds and then show the images and play the sounds

**Comment by yongwang** [comment]
Hi Roger,

Thanks for your detail answer, I have tried to use ffmpeg to convert a rtsp stream into frames of still images and it worked out OK!

regards,
Yong
