### ISSUE TITLE
how to show streaming this images on VLC with RTSP.

### ISSUE THREAD

**Issue by vuonghv1209** [ngraziano/SharpRTSP#12]
Hi,

I build project RtspCameraExample success and then I open connect to **rtsp://10.30.176.31:8554 via VLC**
I think it will show live images YUV type - same video, that project generate from code.
However VLC nothing show any thing, 
So could you help how to show streaming this images on VLC with RTSP.

Thanks and Best Regards!

**Comment by RogerHardiman** [comment]
Can you try the URL with a path after the 8554, e.g.    rtsp://10.30.176.31:8554/h264

**Comment by RogerHardiman** [comment]
Thanks for the bug report.
VLC does not work for me either. I don't think I ever tested with VLC.
When I wrote the example I tested with ffplay.

I will try and see what is wrong.
There may be It is possible that I have something wrong in the SDP data for example the start/end time and the duration (which are missing in the SDP in the example)

**Comment by RogerHardiman** [comment]
I tested with Live555's testRTSPClient. I can see that the NPT value stays as 0.00 on testRTSPClient. This is part of of the presentation time and so this may be the issue with VLC.

**Comment by RogerHardiman** [comment]
UPDATE 2 - I know the cause of the problem.

SharpRTSP with the TinyH264 video encoder does not work with VLC.
SharpRTSP with a proper H264 encoder (libx264) works fine with VLC.

So the problem is that VLC does not like the H264 bitstream generated by TinyH264, but mplayer and ffplay are both fine with the bitstream from TinyH264.

In a real project you would not use TinyH264 anyway. It generates a very high bitrate (it is a loss-less encoder).

So I suggest you try it with a different H264 encoder.

Roger

**Comment by ngraziano** [comment]
Old bug, no response from author. 
VLC work now
