### ISSUE TITLE
how to resize video size(width, height) in sps header?

### ISSUE THREAD

**Issue by fanlovejx** [ngraziano/SharpRTSP#13]
i'm trying to resize video in RTSPCameraExample but it not working then i found that video size has send to rtsp client by sps and pps info, it seem to be too hard for me, please guide me how to resize video header in sps/pps info.

Thank & Best Regards

**Comment by RogerHardiman** [comment]
Hi Fanlovejx
Sorry for the delay in the reply.
RTSPCameraExample is a simple demonstration and it uses the "TinyH264" library written by CardinalPeak which has a fixed image size and a hard coded SPS and PPS.
The SPS and PPS is bit-packed data and requires lots of code to generate so it is not simple to just change a few bytes for the width and height.

When I use the example in my own projects, I replace tiny H264 with a proper H264 library like libx264 and get the SPS, PPS and NALs from libx264

If you wanted to help with the project, there is another open source project that took TinyH264 and added in the SPS and PPS generation code and called in SimpleH264
https://github.com/jordicenzano/h264simpleCoder

That project is written in C++ and the author has given permission to take is code and convert it to C# and use it in SharpRTSP. If you wanted to do this work that would be great and would give us a SharpRTSP example that works with any image size.

But please note that TinyH264 (and SimpleH264) do not compress the video. They transmit losless video (raw video) and so the bandwidth usage is very high. libx264 compresses the video and the bandwidth usage much lower with libx264.
I only use TinyH264 because it was easy to have a complete C# example that runs on any .Net machine (Windows, Mac, Linux) and did not need any external DLLs or interops.


Let me know if you want to port SimpleH264

**Comment by RogerHardiman** [comment]
Update.
I had to do some tests for Fragmenting NALs so ported Jordi Cenzano's SimpleH264 encoder to C# in order to have a test of large NALs (e.g. making a 256x256 image which is more than the 65535 bytes permitted for RTP over RTSP)
This meant I could test Fragmentation (FU-A).

I will add the changes to my fork soon (and then issue a Pull Request).
