### ISSUE TITLE
FFMpeg => RtspMultiplexer return 400 bad request

### ISSUE THREAD

**Issue by ks3dev** [ngraziano/SharpRTSP#30]
1、 Start RtspMultiplexer

2、 Use Command: ffmpeg -i CollectionMercy.flv -vcodec copy -acodec copy -
rtsp_transport tcp -f rtsp rtsp://127.0.0.1:8554

Server Console:
![Image of RtspMultiplexer Console](http://www.ado5.com/out/ex01.png)

FFMpeg Console：
![Image of Cmd FFMpeg Console](http://www.ado5.com/out/ex02.png)

![Image of Cmd FFMpeg Console](http://www.ado5.com/out/ex03.png)

Could you tell me how to use? Thank you!

**Comment by ngraziano** [comment]
Same problem than #18.

RtspMultiplexer do not handle this type of connection, you can only do something like : Video Client (ffmpeg client/vlc) => RtspMultiplexer => Video source (camera for exemple)

I try to handle the functionality for ANNOUNCE from ffmpeg (in branch https://github.com/ngraziano/SharpRTSP/tree/annoncetest) but there is a problem because ffmpeg send data as fast as it can, so it can't be forwarder to another client.

If what you want is serving a file to different client with RTSP, VLC will do the job.

**Comment by ks3dev** [comment]
Could you write a example? I have no idea. Thank you!

**Comment by nu774** [comment]
> I try to handle the functionality for ANNOUNCE from ffmpeg (in branch https://github.com/ngraziano/SharpRTSP/tree/annoncetest) but there is a problem because ffmpeg send data as fast as it can, so it can't be forwarder to another client.

Just try "-re" option of ffmpeg.

### -re (input)
Read input at native frame rate. Mainly used to simulate a grab device, or live input stream (e.g. when reading from a file). Should not be used with actual grab devices or live input streams (where it can cause packet loss). By default ffmpeg attempts to read the input(s) as fast as possible. This option will slow down the reading of the input(s) to the native frame rate of the input(s). It is useful for real-time output (e.g. live streaming).

**Comment by ngraziano** [comment]
@nu774 thanks for the command line tip for ffmpeg.

I have made some test and can handle ffmpeg announce. The code is merged in master and is a bit ugly but it works. I can not take more time to work on this feature but it shows what can be done.

Push with ffmpeg :
`ffmpeg.exe -re -i sample.mp4 -vcodec copy -rtsp_transport udp -f rtsp rtsp://127.0.0.1:8554/PUSH/toto`

And connect PULL from other device in multicast:
`vlc rtsp://192.168.0.11:8554/PULL/toto`
