### ISSUE TITLE
SharpRTSP work with files?

### ISSUE THREAD

**Issue by Dokman** [ngraziano/SharpRTSP#40]
So if i want to stream a video with a presentation inside is possible?

**Comment by RogerHardiman** [comment]
There are no examples for reading video or audio from a file - just an example of receiving video and audio and saving it to a file.
If you wanted to add something as an example it would not be too hard and we could merge you code into the project

**Comment by Dokman** [comment]
okay i'll make a try or something.

**Comment by RogerHardiman** [comment]
What format are you planning to use for the video file?
MP4 or .264 or something else?

**Comment by Dokman** [comment]
mp4 and matroska, but i need a way to read it, so i'll find an algorithm, cause i only need to stream it and the player will do the rest

**Comment by RogerHardiman** [comment]
So there are several parts to this.
1) You need to open the container file (mp4 or mkv) and extract the compressed video data for each frame of video. It will already be compressed (probably H264 in a format called NALs)

2) Then you can look at the RTSP Camera Example. That example generates some video and feeds it into a very simple H264 compressor to get h264 data (called NALs). The example then sends the NALs.
So you will need to read the NALs from the MP4 or MVK file and then you can use the part of the RTSP Camera Example that sends NALs to transmit the video.


(note live555 has code to read files and stream via RTSP if that is any use. I work on SharpRTSP as I have some projects where I need it all in c# either to simplify debugging or due to licences and app store limitations)

**Comment by Dokman** [comment]
i have the same problem as you XD so for this reason i have to use c#

**Comment by Dokman** [comment]
and i have problems with net7mma cause there is no integration about files and i am having a lot of troubles if i open my own apache to stream it

**Comment by RogerHardiman** [comment]
There is some file handling code here https://github.com/juliusfriedman/net7mma/tree/master/Containers

MP4 is known as BaseMedia

**Comment by RogerHardiman** [comment]
Found another library in c#  - 3 clause BSD licence so that is easy to work with

https://github.com/jeremypoulter/basemedia

**Comment by Dokman** [comment]
@RogerHardiman when i use `rtspSource("livestreamname",new Uri("http://localhost/test.mp4"))` doesn't work, so i am f***ed up.

**Comment by RogerHardiman** [comment]
Sorry, don't know what you mean by 'rtspSource'
Which library is that function in?

**Comment by RogerHardiman** [comment]
There are no examples to read from a file and send via RTSP and I don't have time to write one.
So I'll close this Issue.
